const { OpenAI } = require('openai');
const RScoreService = require('./rScoreService');
const { stripHtml } = require('../utils/sanitizeContent');

const localAI = new OpenAI({
  baseURL: process.env.LM_STUDIO_BASE_URL || 'http://127.0.0.1:1234/v1',
  apiKey: process.env.LM_STUDIO_API_KEY || 'lm-studio',
});

const fallbackAI = new OpenAI({
  baseURL: process.env.FALLBACK_BASE_URL || 'https://api.openai.com/v1',
  apiKey: process.env.FALLBACK_API_KEY,
});

const AI_CLIENTS = [
  { client: localAI, model: process.env.LM_STUDIO_MODEL || 'local-model', name: 'local' },
  { client: fallbackAI, model: process.env.FALLBACK_MODEL || 'gpt-4o-mini', name: 'fallback' },
];

const callAI = async (messages, options = {}) => {
  const { temperature = 0.0, max_tokens = 5, stop = ['\n', ' ', '.'], localOnly = false } = options;
  let lastError;

  for (const { client, model, name } of AI_CLIENTS) {
    if (localOnly && name !== 'local') continue;
    if (!client.apiKey) { console.log(`[AI] Skipping ${name}: no API key`); continue; }

    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 60000);

    try {
      const completion = await client.chat.completions.create({
        model,
        messages,
        temperature,
        max_tokens,
        stop,
      }, { signal: controller.signal });

      console.log(`[AI] ${name} model responded`);
      return completion.choices[0].message.content.trim();
    } catch (error) {
      lastError = error;
      console.warn(`[AI] ${name} failed: ${error.message}`);
    } finally {
      clearTimeout(timeout);
    }
  }

  throw lastError || new Error('All AI providers failed');
};

// ✅ 1. Prompt قصير جداً ومباشر (النماذج المحلية تفشل مع التعليمات الطويلة)
const SYSTEM_PROMPT = `You are an AI content moderator.
Analyze the user's text.
If it contains insults, profanity, hate speech, or is unsafe, output exactly: -1
Otherwise, rate its quality from 0 (very poor) to 5 (excellent).
Output ONLY a single number.`;

// 🤖 prompt كشف النص المولّد بالذكاء الاصطناعي (يعتمد النموذج المحلي)
const AI_DETECT_SYSTEM_PROMPT = `You are an AI-text detector.
Estimate the probability that the user's text was generated by an AI.
Output ONLY a single integer from 0 to 100 (no percent sign, no explanation).`;

const evaluateContent = async (content) => {
  const plainText = stripHtml(content);
  if (!plainText?.trim()) return 1;

  try {
    const rawResponse = await callAI(
      [
        { role: 'system', content: SYSTEM_PROMPT },
        { role: 'user', content: plainText },
      ],
      { temperature: 0.0, max_tokens: 5, stop: ['\n', ' ', '.'] }
    );

    console.log('[AI Raw Response]:', rawResponse);
    const match = rawResponse.match(/-?\d+/);
    let score = match ? parseInt(match[0], 10) : 1;

    if (score < -1) score = -1;
    if (score > 5) score = 5;

    return score;
  } catch (error) {
    console.error('[AI Evaluation Error]:', error.message);
    return 1;
  }
};

// تقدير نسبة احتمال أن يكون النص مكتوباً بالذكاء الاصطناعي (يعتمد النموذج المحلي فقط)
const detectAIGenerated = async (content) => {
  const plainText = stripHtml(content);
  if (!plainText?.trim()) return 0;

  try {
    const rawResponse = await callAI(
      [
        { role: 'system', content: AI_DETECT_SYSTEM_PROMPT },
        { role: 'user', content: plainText },
      ],
      { temperature: 0.0, max_tokens: 5, stop: ['\n', ' ', '%', '.'], localOnly: true }
    );

    console.log('[AI Detect Raw Response]:', rawResponse);
    const match = rawResponse.match(/\d+(\.\d+)?/);
    let score = match ? parseFloat(match[0]) : 0;

    if (score < 0) score = 0;
    if (score > 100) score = 100;

    return Math.round(score);
  } catch (error) {
    console.error('[AI Detect Error]:', error.message);
    return null;
  }
};

const processDynamicScoring = (userId, content, actionKey) => {
  setImmediate(async () => {
    try {
      const score = await evaluateContent(content);

      if (score === -1) {
        await RScoreService.applyScore(userId, 'bad_content', 'محتوى غير لائق', -5);
      } else if (score > 0) {
        await RScoreService.applyScore(userId, actionKey, `جودة المحتوى: ${score} نقاط`, score);
      }
    } catch (error) {
      console.error('[Background Task Error]:', error.message);
    }
  });
};

// تقييم بسياق مخصص (للملف الشخصي)
const evaluateWithContext = async (content, systemPrompt) => {
  try {
    const rawResponse = await callAI(
      [
        { role: 'system', content: systemPrompt },
        { role: 'user', content },
      ],
      { temperature: 0.0, max_tokens: 5, stop: ['\n', ' ', '.'] }
    );

    console.log('[AI Context Raw Response]:', rawResponse);
    const match = rawResponse.match(/-?\d+/);
    let score = match ? parseInt(match[0], 10) : 1;

    if (score < 0) score = 0;
    if (score > 5) score = 5;

    return score;
  } catch (error) {
    console.error('[AI Context Evaluation Error]:', error.message);
    return 1;
  }
};

const improveContent = async (text) => {
  if (!text?.trim()) return '';

  try {
    const improved = await callAI(
      [
        {
          role: 'system',
          content: `You are an expert content improver and proofreader for both Arabic and English.
Improve the following text by:
1. Detecting the input language automatically (Arabic or English)
2. Correcting spelling and grammatical errors (even if the original has typos, infer the intended words)
3. Enhancing clarity, professionalism, and scientific accuracy
4. Preserving technical terms exactly (e.g., Frontend, API, Node.js, Full-stack, React, AI)
5. Keeping proper nouns, numbers, and code unchanged
6. Maintaining the original meaning and intent — do NOT change what the user is asking for
7. Using professional modern language (formal Arabic or proper English)

Output ONLY the corrected and improved text in the same language as the input, no explanations, no prefixes, no comments.`,
        },
        { role: 'user', content: text },
      ],
      { temperature: 0.3, max_tokens: 4096, stop: null }
    );

    console.log('[Improve Raw Response]:', improved);
    return improved;
  } catch (error) {
    console.error('[Improve Error]:', error.message);
    throw error;
  }
};

const translateContent = async (text) => {
  if (!text?.trim()) return '';

  try {
    const translated = await callAI(
      [
        {
          role: 'system',
          content: `You are a professional English-to-Arabic translator specialized in technical content.
Translate the following English text to Arabic.
Preserve all technical terms, programming keywords, and proper nouns in their original form (e.g., API, JavaScript, Node.js, Full-stack, Singleton, Observer).
Maintain code snippets, variables, and formatting exactly as-is.
Output ONLY the translated text, no explanations.`,
        },
        { role: 'user', content: text },
      ],
      { temperature: 0.1, max_tokens: 4096, stop: null }
    );

    console.log('[Translate Raw Response]:', translated);
    return translated;
  } catch (error) {
    console.error('[Translate Error]:', error.message);
    throw error;
  }
};

module.exports = { evaluateContent, evaluateWithContext, processDynamicScoring, translateContent, improveContent, detectAIGenerated };